apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${APPLICATION_NAME}
  region: ${AWS_REGION}

iam:
  withOIDC: true

nodeGroups:
  - name: default-nodegroup
    instanceType: t2.medium
    desiredCapacity: 3
