version: "3.3"
services:
  database:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - "./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass