version: "3.3"
services:
  database:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
volumes:
  db_data: