apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-springboot
  name: hello-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-springboot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-springboot
    spec:
      containers:
      - image: cless91/hello-world-springboot:0.0.1-SNAPSHOT
        name: hello-world-springboot
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-springboot
  name: hello-springboot
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: hello-springboot
  type: LoadBalancer

