AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Sample Template ElasticBeanstalk_Simple: Configure and
  launch an AWS Elastic Beanstalk application that connects to an Amazon RDS
  database instance. Monitoring is setup on the database. **WARNING** This
  template creates one or more Amazon EC2 instances and an Amazon Relational
  Database Service database instance. You will be billed for the AWS resources
  used if you create a stack from this template.
Parameters:
  ApplicationName:
    Type: String
    Description: Application Name
  DBName:
    Type: String
    Description: DB Name
  DBUser:
    NoEcho: 'true'
    Type: String
    Description: Test database admin account name
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Type: String
    Description: Test database admin account password
    MinLength: '6'
    MaxLength: '41'
#    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: length must be between 6 and 41.
  OperatorEMail:
    Description: EMail address to notify if there are any operational issues
    Type: String
    AllowedPattern: >-
      ([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)
    ConstraintDescription: must be a valid email address.
  S3Bucket:
    Type: String
    Description: S3 Bucket
  GithubRepo:
    Type: String
    Description: Github source code repository
  GithubRepoBranch:
    Type: String
    Description: Github source code branch
Resources:
  BeanstalkBasedInfra:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'beanstalk/beanstalk-environments.yml'
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        DBName: !Ref DBName
        DBUser:
          Ref: DBUser
        DBPassword:
          Ref: DBPassword
        OperatorEMail:
          Ref: OperatorEMail
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}::BeanstalkBasedInfra'
  BeanstalkBasedPipeline:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: 'beanstalk/beanstalk-pipeline.yml'
      Parameters:
        ApplicationName:
          Ref: ApplicationName
        S3Bucket:
          Ref: S3Bucket
        GithubRepo:
          Ref: GithubRepo
        GithubRepoBranch:
          Ref: GithubRepoBranch
        BeanstalkApplicationName: !GetAtt BeanstalkBasedInfra.Outputs.ApplicationName
        BeanstalkEnvironmentName: !GetAtt BeanstalkBasedInfra.Outputs.EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}::BeanstalkBasedInfra'
