Parameters:
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: Ami Id
  InstanceType:
    Default: t2.micro
    Type: String
    Description: Instance Type
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet Id
  SshKeyName:
    Type: String
    Description: SSH Key Pair Name
  Environment:
    Type: String
    Description: Environment

Resources:
  BastionHostSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ec2 security group
      VpcId: !Ref VpcId
      Tags:
        - Key: Environment
          Value: !Ref Environment
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  BastionHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      KeyName: !Ref SshKeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref BastionHostSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}/BastionHost'
        - Key: Environment
          Value: !Ref Environment
Outputs:
  PublicDnsName:
    Value: !GetAtt [ BastionHost, PublicDnsName ]
  SecurityGroupId:
    Value: !GetAtt [ BastionHostSecurityGroup, GroupId ]